name: "Deploy site"

on:
  push:
    branches: [$default-branch]

  workflow_dispatch:
    # Allow manually running workflow

permissions:
  contents: read
  pages: write
  id-token: write

env:
  OUTPUT: _html

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish:
    name: Publish website
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Lektor
        run: python -m pip install lektor

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build website
        run: lektor build -f htmlmin -O '${{ env.OUTPUT }}'

      #- name: Check for broken internal links
      #  uses: wjdp/htmltest-action@master
      #  with:
      #    path: ${{ env.OUTPUT }}
      #    config: .htmltest.yml
      #    skip_external: true
      #    log_level: 1

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.OUTPUT }}

      - name: Deploy website
        id: deployment
        uses: actions/deploy-pages@v4
